language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
# command to install dependencies
install:
# develop seems to be required by travis since 02/2013
#  - python setup.py build develop
  - pip install nose
# command to run tests
script:
  - nosetests
notifications:
  email: false
